import { Nav } from "@/components/Nav"
import "./globals.css"
import Footer from "@/components/Footer/Footer"

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className='h-screen w-screen flex  flex-col bg-black font-bold'>
				<div className='flex h-main px-2 pt-2'>
					<Nav />
					<main className='w-full rounded-lg bg-gray px-6 pt-6 text-white'>{children}</main>
				</div>
				<Footer />
			</body>
		</html>
	)
}
