"use client"
import { Nav } from "@/components/Nav"
import "./globals.css"
import Footer from "@/components/Footer/Footer"
import { AppProvider } from "./context/AppContext"

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export const RootLayout = ({ children }: { children: React.ReactNode }) => {
	return (
		<html lang='en'>
			<body className='h-screen w-screen flex  flex-col bg-black font-bold'>
				<AppProvider>
					<div className='flex h-main px-2 pt-2'>
						<Nav />
						<main className='w-full rounded-lg bg-gray px-6 pt-6 text-white'>
							{children}
						</main>
					</div>
					<Footer />
				</AppProvider>
			</body>
		</html>
	)
}

export default RootLayout
